# Generated by Django 3.2.5 on 2021-10-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20211014_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='modify_date',
        ),
    ]
